name: FancyCoins
main: de.oliver.fancycoins.FancyCoins
author: OliverHD
version: 1.0.0
api-version: 1.19
loadbefore:
  - Vault
commands:
  FancyCoins:
    permission: FancyCoins.admin
  Coins:
    aliases:
      - money
      - bal
      - balance
  Pay: