name: FancyEconomy
description: $description
authors: [ OliverHD ]
contributors: [ mani1232 ]
version: $version
website: https://github.com/FancyMcPlugins/FancyEconomy
main: de.oliver.fancyeconomy.FancyEconomy
api-version: 1.19
folia-supported: true
softdepend:
  - Vault
  - PlaceholderAPI