name: FancyEconomy
main: de.oliver.fancyeconomy.FancyEconomy
authors: [ OliverHD ]
contributors: [ mani1232 ]
version: 1.0.1
api-version: 1.19
website: https://github.com/FancyMcPlugins/FancyEconomy
softdepend:
  - Vault
  - PlaceholderAPI