name: FancyCoins
main: de.oliver.fancycoins.FancyCoins
authors: [ OliverHD ]
contributors: [ mani1232 ]
version: ${projectVersion}
description: ${projectDescription}
api-version: 1.19
website: https://github.com/FancyMcPlugins/FancyCoins
loadbefore:
  - Vault